### ISSUE TITLE
NameError: name 'driver' is not defined

### ISSUE THREAD

**Issue by hista** [vadimkantorov/natudump#1] opened 2022-12-03 23:10 UTC
Hi,
I face an issue with the use of your scrapper.

```
python3 natudump.py   -o jo --years $(seq 2000 2021) --output-directory-prefix "$PWD/"
Namespace(jo_search='https://www.legifrance.gouv.fr/jorf/jo/{year}?page={page}&pageSize=100', jo_download='https://www.legifrance.gouv.fr/download/secure/file/{token}', years=[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021], output_directory='jo', output_directory_prefix='/home/hista/natudump/', chromedriver='/usr/bin/chromedriver', timeout=10.0, timeout_big=30.0, headmore=False, debug='debug.html')
Message: session not created: Missing or invalid capabilities
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 6.0.0-5-amd64 x86_64)

Page 1 big timeout
Traceback (most recent call last):
  File "/home/hista/natudump/natudump.py", line 86, in <module>
    driver = selenium.webdriver.Chrome(options = chrome_options, service = chrome_service)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Missing or invalid capabilities
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 6.0.0-5-amd64 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hista/natudump/natudump.py", line 153, in <module>
    driver.quit()
NameError: name 'driver' is not defined
```

Could you please tell me how to fix it?
Thanks for your kind help

**Comment by vadimkantorov** [comment] 2022-12-05 13:24
In general, please make sure that your chromedriver path parameter, chromedriver version and chrome path are matching and correct. The problem is in initializing Chrome driver. You can try to do this by running way more basic selenium tutorials using Chrome and chromedriver and googling the `selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Missing or invalid capabilities` error message. Once you succeed, feel free to backport these fixes to natudump. Happy to take PRs.

I fixed the issue with driver.quit() being called on non-existent driver, but apart from that I don't have any special knowledge and can't help, you'll need to debug this yourself. Good luck! I'm closing this issue for now, but if you find a fix, feel free to comment or send a PR.

**Closed as completed by vadimkantorov** 2022-12-05 13:24 UTC
